ALTER LOGIN HEALTHTECH\GS-ADM-TSS Database Support Group DISABLE
ALTER LOGIN HEALTHTECH\LS-RL-HSS-SQL Servers Administrators DISABLE
ALTER LOGIN HEALTHTECH\adm_kumarans DISABLE
ALTER LOGIN NSWHEALTH\U-SRES-TrakGenePowerUsers DISABLE
ALTER LOGIN NSWHEALTH\SRV-NSWH-TrakGeneClu DISABLE
ALTER LOGIN NSWHEALTH\L-SRES-TrakGeneProdUsers DISABLE
ALTER LOGIN HEALTHTECH\TSS DBA DISABLE
ALTER LOGIN NSWHEALTH\L-SRES-TrakGeneTestUsers DISABLE
ALTER LOGIN NSWHEALTH\L-SRES-TrakGeneAdminUsers DISABLE
ALTER LOGIN HEALTHTECH\yungg DISABLE
ALTER LOGIN HEALTHTECH\adm_CullingB DISABLE
ALTER LOGIN HEALTHTECH\adm_tansusan DISABLE
ALTER LOGIN test DISABLE
ALTER LOGIN NSWHEALTH\adm_60135702 DISABLE
ALTER LOGIN HEALTHTECH\ADM_MTrikha DISABLE
ALTER LOGIN HEALTHTECH\adm_60151019 DISABLE
ALTER LOGIN NSWHEALTH\adm_23500105 DISABLE
ALTER LOGIN NSWHEALTH\adm_60147731 DISABLE
ALTER LOGIN NSWHEALTH\L-STA-HIaaSLocalDBAadmins DISABLE
ALTER LOGIN NSWHEALTH\ADM_60128477 DISABLE
ALTER LOGIN HEALTHTECH\adm_VandiemenK DISABLE
ALTER LOGIN NSWHealth\adm_40037556 DISABLE